### ISSUE TITLE
Small suggestion for exported types

### ISSUE THREAD

**Issue by vladfrangu** [TheMrGong/discord.js-interactions-api#1]
Hello!

I noticed you use our module, `discord-api-types` (thanks btw, ❤️), and I noticed you re-did some of the REST types (https://github.com/TheMrGong/discord.js-interactions-api/blob/b50c1f356c4ca361f14151a340f736c68ef5f685/lib/types.d.ts#L15-L31)

We export REST types too, prefixed with the `REST` header, and they might help you stay up to date without needing to maintain a set of types too! It is, of course, up to you if you want to use them, but I thought I'd let you know (if you didn't know already) 😅 

Have a good day!

**Comment by TheMrGong** [comment]
Ah thank you! I looked around for those but I must've missed they were prefixed with REST
